version: '3.8'

x-load-secrets-config: &load-secrets-config
  configs:
    - source: load-secrets.sh
      target: /usr/local/bin/load-secrets.sh
      mode: 0555

services:
  database:
    image: docker-swarm-01.local:5000/monorepo-template/database:1.0.0
    secrets:
      - monorepo-template_DB_PASSWORD
    <<: *load-secrets-config
    environment:
      PROJECT_NAME: monorepo-template
      POSTGRES_DB: monorepo-template
      POSTGRES_USER: app
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      labels:
        - 'traefik.enable=false'

  migrations:
    image: docker-swarm-01.local:5000/monorepo-template/drizzle:1.0.0
    secrets:
      - monorepo-template_DB_PASSWORD
    <<: *load-secrets-config
    environment:
      PROJECT_NAME: monorepo-template
      DB_USER: app
      DB_NAME: monorepo-template
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 120s
      labels:
        - 'traefik.enable=false'

  app:
    image: docker-swarm-01.local:5000/monorepo-template/app:1.7.0
    secrets:
      - monorepo-template_DB_PASSWORD
      - monorepo-template_BETTER_AUTH_SECRET
      - monorepo-template_RESEND_API_KEY
      - monorepo-template_GOOGLE_CLIENT_SECRET
      - monorepo-template_GITHUB_CLIENT_SECRET
    <<: *load-secrets-config
    environment:
      PUBLIC_BASEURL: https://donut.yaoshiko.com
      PROJECT_NAME: monorepo-template
      DB_USER: app
      DB_NAME: monorepo-template
      DB_HOST: database
      DB_PORT: 5432
    depends_on:
      - migrations
    networks:
      - app-network
      - portainer_reverse-proxy-network
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.app.rule=PathPrefix(`/`)'
        - 'traefik.http.routers.app.entrypoints=websecure'
        - 'traefik.http.routers.app.tls.certresolver=myresolver'
        - 'traefik.http.services.app.loadbalancer.server.port=3000'
      mode: global
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:

networks:
  app-network:
  portainer_reverse-proxy-network:
    external: true

secrets:
  monorepo-template_DB_PASSWORD:
    external: true
  monorepo-template_BETTER_AUTH_SECRET:
    external: true
  monorepo-template_RESEND_API_KEY:
    external: true
  monorepo-template_GOOGLE_CLIENT_SECRET:
    external: true
  monorepo-template_GITHUB_CLIENT_SECRET:
    external: true

configs:
  load-secrets.sh:
    external: true
